# Generated by Django 3.0.5 on 2020-04-02 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_manthan'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Manthan',
        ),
    ]
