# Generated by Django 3.0.5 on 2020-04-05 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0005_manthan'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Manthan',
        ),
    ]
