# Generated by Django 3.0.5 on 2020-04-05 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Blog', '0006_delete_manthan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manthan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.ImageField(upload_to='')),
                ('name', models.CharField(max_length=20)),
                ('address', models.TextField(max_length=50)),
                ('contact', models.IntegerField()),
                ('mail', models.EmailField(max_length=30)),
            ],
        ),
    ]
