# Generated by Django 3.0.5 on 2020-04-12 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0007_manthan'),
    ]

    operations = [
        migrations.AddField(
            model_name='manthan',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
